 * Serving Flask app "application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
67.188.59.82 - - [26/Oct/2019 09:03:53] "GET / HTTP/1.1" 200 -
14.102.94.82 - - [26/Oct/2019 10:16:52] "GET / HTTP/1.1" 200 -
47.99.215.199 - - [26/Oct/2019 11:48:39] "GET /TP/public/index.php HTTP/1.1" 404 -
47.99.215.199 - - [26/Oct/2019 11:48:40] "GET /TP/index.php HTTP/1.1" 404 -
47.99.215.199 - - [26/Oct/2019 11:48:42] "GET /thinkphp/html/public/index.php HTTP/1.1" 404 -
47.99.215.199 - - [26/Oct/2019 11:48:43] "GET /html/public/index.php HTTP/1.1" 404 -
47.99.215.199 - - [26/Oct/2019 11:48:45] "GET /public/index.php HTTP/1.1" 404 -
47.99.215.199 - - [26/Oct/2019 11:48:46] "GET /TP/html/public/index.php HTTP/1.1" 404 -
47.99.215.199 - - [26/Oct/2019 11:48:48] "GET /elrekt.php HTTP/1.1" 404 -
47.99.215.199 - - [26/Oct/2019 11:48:53] "GET / HTTP/1.1" 200 -
221.217.98.243 - - [26/Oct/2019 12:24:27] "GET / HTTP/1.0" 200 -
66.249.73.65 - - [26/Oct/2019 12:24:33] "GET /robots.txt HTTP/1.1" 404 -
66.249.73.71 - - [26/Oct/2019 12:24:33] "GET / HTTP/1.1" 200 -
196.52.43.52 - - [26/Oct/2019 13:14:53] "GET / HTTP/1.0" 200 -
222.186.130.22 - - [26/Oct/2019 13:52:44] "GET /TP/public/index.php HTTP/1.1" 404 -
222.186.130.22 - - [26/Oct/2019 13:52:45] "GET /TP/index.php HTTP/1.1" 404 -
222.186.130.22 - - [26/Oct/2019 13:52:48] "GET /thinkphp/html/public/index.php HTTP/1.1" 404 -
222.186.130.22 - - [26/Oct/2019 13:52:49] "GET /html/public/index.php HTTP/1.1" 404 -
222.186.130.22 - - [26/Oct/2019 13:52:49] "GET /public/index.php HTTP/1.1" 404 -
222.186.130.22 - - [26/Oct/2019 13:52:51] "GET /TP/html/public/index.php HTTP/1.1" 404 -
222.186.130.22 - - [26/Oct/2019 13:52:54] "GET /elrekt.php HTTP/1.1" 404 -
222.186.130.22 - - [26/Oct/2019 13:52:54] "GET /index.php HTTP/1.1" 404 -
222.186.130.22 - - [26/Oct/2019 13:52:55] "GET / HTTP/1.1" 200 -
139.162.106.181 - - [26/Oct/2019 14:20:51] "GET / HTTP/1.1" 200 -
67.188.59.82 - - [26/Oct/2019 15:01:32] "GET / HTTP/1.1" 200 -
67.188.59.82 - - [26/Oct/2019 15:01:32] "GET /favicon.ico HTTP/1.1" 404 -
172.58.37.231 - - [26/Oct/2019 15:05:13] "GET / HTTP/1.1" 200 -
172.58.37.231 - - [26/Oct/2019 15:05:13] "GET /favicon.ico HTTP/1.1" 404 -
Traceback (most recent call last):
  File "application.py", line 14, in <module>
    application.config['UPLOAD_FOLDER'] = config['flask']['upload_folder']
  File "/home/ubuntu/.local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1040, in __getitem__
    raise KeyError(key)
KeyError: 'flask'
Traceback (most recent call last):
  File "application.py", line 41, in <module>
    @app.route('/', methods=['GET', 'POST'])
NameError: name 'app' is not defined
 * Serving Flask app "application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "application.py", line 74, in <module>
    application.run(host='0.0.0.0', port=80)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 963, in inner
    fd=fd,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 806, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
 * Serving Flask app "application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
67.188.59.82 - - [26/Oct/2019 18:32:05] "GET /upload HTTP/1.1" 200 -
67.188.59.82 - - [26/Oct/2019 18:32:15] "GET / HTTP/1.1" 302 -
67.188.59.82 - - [26/Oct/2019 18:32:26] "GET / HTTP/1.1" 302 -
 * Serving Flask app "application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "application.py", line 74, in <module>
    application.run(host='0.0.0.0', port=80)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 963, in inner
    fd=fd,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 806, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/ubuntu/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
 * Serving Flask app "application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
67.188.59.82 - - [26/Oct/2019 18:34:40] "GET / HTTP/1.1" 302 -
 * Serving Flask app "application" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
67.188.59.82 - - [26/Oct/2019 18:36:50] "GET / HTTP/1.1" 302 -
67.188.59.82 - - [26/Oct/2019 18:36:59] "GET /upload?code=eyJ0eXAiOiJNVCIsImFsZyI6IlJTMjU2Iiwia2lkIjoiNjgxODVmZjEtNGU1MS00Y2U5LWFmMWMtNjg5ODEyMjAzMzE3In0.AQoAAAABAAYABwAAAaZ7Q1rXSAgAAI0sw0Na10gCAFLaV4dIEQdGsyhSu2ZjyFMVAAEAAAAYAAEAAAAFAAAADQAkAAAANTQzY2NhYjgtNDliMS00ZmRlLThkZWItMTI0Zjg5YTk0M2Y0MAAAAaZ7Q1rXSBIAAQAAAAsAAABpbnRlcmFjdGl2ZTcAxmSPn0vcd0CZ41ACLhszzA.oRR4M-GWDfdavayTIHuVxX9muXtNfUgBbPTnjPxik9NNILo0wjHWRJkYqU8wC0Yyw1V1QOri03YxynJ75zgfp9TLKWPvCwoGHOMgmKg6C84HQYsOc2DcC4RtkyzrDiLTaEcTBfaUOAqSdghwMLhMOydYhNhnRHLe53zZtg8twF9E48D2YZD9MKXBmIm_TzWZDbNWZgoQO0UHMp7kt38s2dHAUtrkplfDE9yl76eZWczBLx06y5gefafvwh8iwHl7jBmL5ZFnLebOxJ3UB9GEHmkcuROGUUmvaZakdA_tg283dpoCq2aLpUiWpzxYLjWSqKU-u2yJ0iMbp8UCyypA_A HTTP/1.1" 200 -
Traceback (most recent call last):
  File "application.py", line 3, in <module>
    import requests
ImportError: No module named requests
